#ifndef FR_SHAREDDEFS_H
#define FR_SHAREDDEFS_H

#ifdef _WIN32
#pragma once
#endif

#include "const.h"
#include "Color.h"
#include "shareddefs.h"

//START FR ACHIVEMENTS
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20COMBINE					151
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50COMBINE					152
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100COMBINE				153
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20HUNTERS					154
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50HUNTERS					155
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100HUNTERS				156
#define ACHIEVEMENT_FIREFIGHTRELOADED_REACHMAXLEVEL					157
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ENEMIES				158
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILLTHOUSANDENEMIES			159
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILLMILLIONENEMIES			160
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILLCOMBINEWITHFLECHETTE		161
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10HUNTERSWITHFLECHETTE	162
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ENEMIESONNIGHTMARE		163
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ANTLIONS				164
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50ANTLIONS				165
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ANTLIONS				166
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ANTLIONGUARDS			167
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50ANTLIONGUARDS			168
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ANTLIONGUARDS			169
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ZOMBIES					170
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50ZOMBIES					171
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ZOMBIES				172
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20HEADCRABS				173
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50HEADCRABS				174
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100HEADCRABS				175
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20XENCREATURES			176
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL50XENCREATURES			177
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100XENCREATURES			178
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESWITHGRENADE		179
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESZEROBULLETS		180
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL20ENEMIESNODAMAGE			181
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESATLOWHEALTH		182
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL100ENEMIESONDEATH			183
#define ACHIEVEMENT_FIREFIGHTRELOADED_KILL10ENEMIESWITHOWNGRENADE	184
//ENDGAME
#define ACHIEVEMENT_FIREFIGHTRELOADED_COMPLETEDBOSSFIGHT			185
#define ACHIEVEMENT_FIREFIGHTRELOADED_COMPLETEDTUTORIAL				186
//INVASION
#define ACHIEVEMENT_FIREFIGHTRELOADED_MAXKATANAMULTIPLIER			187
#define ACHIEVEMENT_FIREFIGHTRELOADED_SKYBORNEPIN					188
#define ACHIEVEMENT_FIREFIGHTRELOADED_MULTIKILLSTREAK				189
#define ACHIEVEMENT_FIREFIGHTRELOADED_SKYBORNEDECAP					190
//END FR ACHIEVEMENTS

enum FirefightPrimaryGamemodes
{
	FIREFIGHT_PRIMARY_DISABLED = -1,
	FIREFIGHT_PRIMARY_DEFAULT,
	FIREFIGHT_PRIMARY_COMBINEFIREFIGHT,
	FIREFIGHT_PRIMARY_XENINVASION,
	FIREFIGHT_PRIMARY_ANTLIONASSAULT,
	FIREFIGHT_PRIMARY_ZOMBIESURVIVAL,
	FIREFIGHT_PRIMARY_FIREFIGHTRUMBLE
};

enum FR_ItemTypes_t
{
	FR_HEALTHKIT = 1,
	FR_BATTERY,
	FR_HEALTHKIT_BIG,
	FR_BATTERY_BIG,
	FR_WEAPON,
	FR_AMMOWEAPON,
	FR_AMMO,
	FR_PERK,
	FR_KASHBONUS,
	FR_SERVERCMD,
	FR_CLIENTCMD,
	FR_EXPBONUS
};

enum FR_PerkIDs_t
{
	FIREFIGHT_PERK_INFINITEAUXPOWER = 1,
	FIREFIGHT_PERK_INFINITEAMMO,
	FIREFIGHT_PERK_HEALTHREGENERATIONRATE,
	FIREFIGHT_PERK_HEALTHREGENERATION
};

enum FR_UpgradeIDs_t
{
	FIREFIGHT_UPGRADE_MAXHEALTH,
	FIREFIGHT_UPGRADE_EXPBOOST,
	FIREFIGHT_UPGRADE_KASHBOOST,
	FIREFIGHT_UPGRADE_HEALTHREGENERATION_RANGE,

	FIREFIGHT_UPGRADE_MAX
};

#define MAX_LEVEL 20

//FR COLORS
#define COLOR_FR_OLD	Color(84, 84, 255, 255)
#define COLOR_FR		Color(0, 120, 255, 255)

//FR FUN COLORS
#define COLOR_PURPLE	Color(199, 154, 245, 255)
#define COLOR_CYAN		Color(73, 216, 245, 255)
#define COLOR_TURQUOISE	Color(56, 245, 210, 255)
#define COLOR_PINK		Color(237, 142, 220, 255)
#define COLOR_MAGENTA	Color(255, 0, 255, 255)
#define COLOR_YELLOW_NEW	Color(245, 196, 73, 255)

//FR NPC TEAMS. Player still gets TEAM_UNASSIGNED. Used for death notices.
#define TEAM_RED		2
#define TEAM_BLUE		3
#define TEAM_YELLOW		4
#define TEAM_GREEN		5
#define TEAM_GREY		6
#define TEAM_WHITE		7
#define TEAM_BLACK		8
#define TEAM_PURPLE		9
#define TEAM_ORANGE		10
#define TEAM_CYAN		11
#define TEAM_TURQUOISE	12
#define TEAM_PINK		13
#define TEAM_MAGENTA	14

//CHANGE THESE IF YOU ADD A NEW TEAM
#define TEAM_NPC_FIRST	TEAM_RED
#define TEAM_NPC_LAST	TEAM_MAGENTA

#define TEAM_RANDOM		15

typedef struct
{
	int id;
	Color col;
} FRTeam_t;

class CFRTeamLoader
{
public:
	static FRTeam_t FRTeamMap[];
	static Color GetColorForTeam(int iTeamNumber);
	static void LoadColors(Color *colorArray);
};

#endif // FR_SHAREDDEFS_H