#ifndef TASKS_SHARED_H
#define TASKS_SHARED_H
#ifdef _WIN32
#pragma once
#endif

#define TASKLIST_MAX_TASKS 5

#define TASKLIST_KILL_TASK_MIN_KILL_RARE_COUNT 1
#define TASKLIST_KILL_TASK_MIN_KILL_COUNT 2
#define TASKLIST_KILL_TASK_MAX_KILL_COUNT 5
#define TASKLIST_KILL_TASK_COUNTTOCHANGECOLOR 3

#define TASKLIST_MAX_COUNT 255

enum eTaskPriority
{
	TASK_INACTIVE = 0,
	TASK_COMPLETE,
	TASK_LOW,
	TASK_MEDIUM,
	TASK_HIGH
};

enum eTaskType
{
	TASK_KILL = 0,
	TASK_TYPE_LAST
};

#endif