name: FR_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
  pull_request:
   paths:
      - 'sp/src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Install Registry Key
        run: REG ADD "HKLM\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v DefaultProjectExtension /t REG_SZ /d vcproj /f

      - name: Install VS 2013 Build Tools
        run: choco install microsoft-build-tools-2013
        
      - name: Create project
        run: cd sp/src;devtools/bin/vpc.exe /fr +gameandtools /mksln firefight.sln

      - name: Build project
        run: cd "C:/Program Files (x86)/MSBuild/12.0/Bin"; msbuild.exe /m /p:PlatformToolset=v120_xp /p:Configuration=Release /p:Platform=x86 D:\a\FIREFIGHT-RELOADED-src-sdk-2013\FIREFIGHT-RELOADED-src-sdk-2013\sp\src\firefight.sln

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz sp/game

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: firefightreloaded_windows
          path: Windows.tar.xz
